## numpy(Numerical Python)
- Open Source Python 라이브러리
- 다차원배열(ndarray)과 행렬 연산을 수행할 수 있는 구조로 되어있다.

넘파이는  
넘파이배열(ndarray) 라는 자료구조를 사용  
- 백터나 행렬 등의 연산을 쉽고 빠르게 수행

In [4]:
# numpy 설치 
! pip install numpy
# 주피터에선 !를 꼭 붙여줘야함


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
# numpy array는 numpy array끼리 연산이 가능
# 0~9까지 파이썬 리스트를 만들어보자
pa=list(range(10))
pb=pa

print('pb+pb:', pb + pa)

import numpy as np
na=np.arange(10)
print('na:', na)
# 1차원 어레이(배열),에이레인지..
# 빌트인 레인지 엔디맨션 어레이..? --> 모든 걸 일차원의 평면으로 보기 때문
nb=na
# 
print('na+nb:', na + nb) # 연산을 함!! ㄷㄷ 

# Broadcasting
print('na*4:', na*4)

print('pa*4:' ,pa*4)

print(type(na)) # numpy.ndarray

pb+pb: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
na: [0 1 2 3 4 5 6 7 8 9]
na+nb: [ 0  2  4  6  8 10 12 14 16 18]
na*4: [ 0  4  8 12 16 20 24 28 32 36]
pa*4: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>


## Numpy 배열
- 모든 배열의 값이 기본적으로 같은 타입
- 각 차원(Dimension)을 축(axis) 표현

In [6]:
# shape(3, )
[1,2,3]
# shape(2,3)
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [7]:
a=[[1,2,3],[4,5,6]]
b=np.array(a)
print(a)
print(b)
print(b.shape)
print(b[1,2])

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [24]:
a=np.arange(10,dtype=np.float32)
print(a,a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float32


In [31]:
a=np.arange(12)
print(a)
#1차원을 2차원으로 차원 변경 빌트인 함수
b=a.reshape(2,6) # 구간 선정 잘하기
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [33]:
a= np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### numpy 배열 대표 속성값
- shape: 배열의 각 축(axis)의 크기  
- ndim: 축의 개수
- dtype: 각 요소의 타입
- itemsize: 각 요소의 타입의 크기(byte)
- size: 전체요소의 개수

In [36]:
print('a:', a)
print()
print('a.shape:',a.shape)
print()
print('a.ndim:',a.ndim)
print()
print('a.itemsize:',a.itemsize)
print()
print('a.size:',a.size)

a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a.shape: (3, 4)

a.ndim: 2

a.itemsize: 4

a.size: 12


## 넘파이 배열 생성방법
np.array() 이용하여 tuple이나 list를 통해 ndarray를 생성  

In [8]:
a= np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [9]:
b= np.array([1.2,-3.5, 5.1])
print(b,type(b), b.dtype)
# 튜플은 대괄호 대신에 소괄호로

[ 1.2 -3.5  5.1] <class 'numpy.ndarray'> float64


In [10]:
arr = np.array([1,2,3,4,5])
arr.dtype
# 타입변경 astype
arr_float=arr.astype(np.float32)
print('arr', arr.dtype)
print('arr_float',arr_float.dtype)

arr int32
arr_float float32


In [11]:
num_str=np.array([1.234,-2.29,1000])
print(num_str, num_str.dtype)

[   1.234   -2.29  1000.   ] float64


In [53]:
num_str=num_str.astype(np.string_)
print(num_str, num_str.dtype)

[b'1.234' b'-2.29' b'1000.0'] |S32


In [56]:
arr_str=np.array(list(map(lambda x: x.decode(), num_str))) # binary string을 string으로 변환
# 리스트로도 가능 arr_str=np.array([x.decode() for x in num_str])
print(arr_str, type(arr_str), arr_str.dtype, arr_str.ndim)
print(arr_str[0])

['1.234' '-2.29' '1000.0'] <class 'numpy.ndarray'> <U6 1


'1.234'

### 다양한 차원의 배열 생성
파라미터로 shape 를 주는데 shape는 축을 얘기함
- np.zeros(shape) : 0으로 구성된(채워진) n차원 배열
- np.ones(shape) : 1로 구성된 n차원 배열
- np.empty(shape) : 초기화하지 않은 n차원 배열
- np.full(shape,value) : value로 채워진 n차원 배열

In [12]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [60]:
print(np.ones((2,3,4), dtype=np.int64))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


맨앞에 []기준으로 개수를 세면 쉽다.  
맨 처음 []안에 개수, 2번째 []안에 개수, 컬럼수  

[[[1 1 1 1]  
  [1 1 1 1]  
  [1 1 1 1]]  
  
 [[1 1 1 1]  
  [1 1 1 1]  
  [1 1 1 1]]]  
  
shape(2,3,4)  
  
대괄호 개수로 생각.  
(3,4)의 shape을 가진 2차원 array가 2개가 있는 3차원 array  

In [62]:
a= np.ones((2,3,4))
a.shape

(2, 3, 4)

In [64]:
print(np.empty((2,3)))

[[2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [1.48539705e-313 1.90979621e-313 2.33419537e-313]]


In [65]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

np.arange() : n-1 만큼 숫자 생성  
np.linspace() : n등분만큼 숫자 생성

In [69]:
print(np.arange(10, 30))
print(np.arange(10,30,5))

print()
print(np.linspace(0,99,10)) # 0에서 99까지 10등분해서 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 15 20 25]

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


In [72]:
# 0.25씩 차이나도록 0부터 1까지 step으로 출력
print(np.arange(0,1+0.25, 0.25))

# 0부터 1까지 5등분으로 출력
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


In [76]:
# 0부터 5까지 1차원 어레이 만들기
a=np.arange(0,6)
print(a, a.ndim, a.shape)
# 4,3의 shape으로 2차원 배열로 출력
b=a.reshape(2,3)
print(b)

[0 1 2 3 4 5] 1 (6,)
[[0 1 2]
 [3 4 5]]


In [77]:
# arange를 활용해서 (2,3,4)의 3차원 배열을 만드시오.
a=np.arange(24)
b=a.reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## numpy 기본연산
- 차원(축=axis) 기준으로 행렬내에 같은 위치에 있는 원소끼리 연산ㅇ르 하는 방식

In [13]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [14]:
c=a-b
print(c)

[10 19 28 37]


In [15]:
b**2 # 각 원소에 제곱연산 수행
print(b) # but, 원본을 훼손하지 않고 연산을 수행함!! 대박이쥬?

[0 1 2 3]


In [91]:
c= a<25 # boolean 결과값을 표현 
# 만약 list로 하면 하나하나~~~
# but, numpy로 하면 연산이 아~~주 쉬워요~~
print(c)
print(a)

[ True  True False False]
[10 20 30 40]


In [92]:
a[c]
a[a>25] #도 가능
print(a) # a(원본)은 변화가 없다.

[10 20 30 40]


In [99]:
# 3 x 4 배열을 만들고 (0 부터 11까지)
myarr=np.arange(0,12). reshape(3,4)
print('myarr',myarr,'\n')
# [Bob, Joe, Bob]를 가진 1차원 array를 선언
myarr_str=np.array(['Bob', 'Joe', 'Bob'])
print('myarr_str', myarr_str,'\n')
# Bob에 해당하는 인덱스만 3 x 4 array에서 출력해보자.
print(myarr[myarr_str=='Bob'])

myarr [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

myarr_str ['Bob' 'Joe' 'Bob'] 

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [101]:
myarr[myarr_str=='Bob', 1:3] # 원하는 컬럼의 행만 뽑아오기 --> 파이썬의 슬라이싱 연산자 사용

array([[ 1,  2],
       [ 9, 10]])

In [105]:
# Bob에 해당하는 행에 1행만 출력하고자 한다면
myarr[myarr_str=='Bob'][1]

array([ 8,  9, 10, 11])

In [107]:
myarr_str=np.array(['Bob','Joe','Wil'])
mask=(myarr_str=='Bob') | (myarr_str=='Wil') # 마스킹
print(mask)

[ True False  True]


In [119]:
# 2,3
# 10,11
# 위의 값들을 0으로 변경하고자 한다면
print(myarr)
myarr[mask,2:4]=0
print(myarr[mask])

# y[:,2:]=0


[[0 1 0 0]
 [4 5 6 7]
 [8 9 0 0]]
[[0 1 0 0]
 [8 9 0 0]]


In [121]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr1,arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 0.,  4.,  1.],
        [ 7.,  2., 12.]]))

In [123]:
arr1<arr2

array([[False,  True, False],
       [ True, False,  True]])

In [125]:
(arr1<arr2).sum()

3

In [137]:
# 8 x 4 빈배열을 하나만들고
# 각 행마다 1행에는 0의 값을 ,2행에는 1의 값을 ... 넣어보자

emptyarr=np.empty(shape=(8,4))
print(emptyarr)

for i in range(8):
    emptyarr[i]=i

print(emptyarr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [134]:
emptyarr[[4,0,7,1]] # 정수 인덱싱 가능

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [1., 1., 1., 1.]])

In [138]:
emptyarr[[-4,-5,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [140]:
print(emptyarr) #원본데이터는 고대로

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [17]:
emptyarr=np.arange(32).reshape(8,4)
print(emptyarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [18]:
# 다중 인덱싱(정수만 이럼)
emptyarr[[1,5,7,2],[0,3,1,2]] 
#(1,0), (5,3), (7,1), (2,2)

# 부울 인덱싱으로도 가능하고 정수로도 가능한데 정수로 들어가면 각 행들의 값으로 됨

array([ 4, 23, 29, 10])

## 기본연산
- *: 각각 원소끼리 곱셉
- @: 행렬 곱셈

In [149]:
A=np.array(np.arange(4)).reshape(2,2)
B=A
print(A)
# 각각의 원소끼리 곱셈
print(A*B)
# 행렬 곱
print(A@B)

# [0,1] [2,3]
# [0,1] [2,3]

[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]


In [154]:
# 형변환
a=np.ones(3, dtype=np.int32)
print(a)
b=np.linspace(0,np.pi,3)
print(b.dtype)

[1 1 1]
float64


In [156]:
c=a+b
print(c,c.dtype) # 큰 쪽으로 타입이 변경됨
# int < float < complex

[1.         2.57079633 4.14159265] float64


## 집계 함수
- sum() : 모든 요소의 합
- min() : 모든 요소 중 최소값
- max() : 모든 요소 중 최대값
- argmax() : 모든 요소 중 최대값의 인덱스
- cumsum() : 모든 요소의 누적합

In [19]:
# 0~7 제곱된 값을 2,4 크기로 출력
arr=np.arange(8).reshape(2,4)**2

print(arr)
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.argmax())
print(arr.cumsum())

[[ 0  1  4  9]
 [16 25 36 49]]
140
0
49
7
[  0   1   5  14  30  55  91 140]


In [167]:
arr=np.arange(9).reshape(3,3)
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))
print(arr.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
[ 3 12 21]


## 넘파이 범용함수(nuiversal function)
- 구글링해보삼 (numpy.org는 너무 번거로움)

In [ ]:
B=np.array([1,4,9])
np.sqrt(B)

## numpy 인덱싱과 슬라이싱

In [23]:
a=np.arange(10)**2
print(a)

print(a[2]) # 4출력을 위해 인덱스 사용

print(a[2:5]) # 4,9,16 출력 , 1차원이니까 요로케

print(a[::-1]) # 모든 인덱스를 거꾸로 출력

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 4  9 16]
[81 64 49 36 25 16  9  4  1  0]


In [24]:
# 0, 4, 16를 출력하시오
print(a[0:5:2]) # 0~4까지 인덱스에 2step으로 요소를 뽑아라.

[ 0  4 16]


In [25]:
a[0:5:2]=1000
print(a)

arr_slice=a[5:8]
print(arr_slice)

[1000    1 1000    9 1000   25   36   49   64   81]
[25 36 49]


배열 슬라이스는 새로운 객체를 만드는 것이 아닌 배열에 대한 view를 가진다.  
즉, 잘라낸 배열에 값을 변경했을 때(대입연산자) 원본값도 변경된다.

In [182]:
# 파이썬 리스트와 numpy리스트가 크게 다른 것: 새로운 arr_slice에 넣어도 a리스트에도 반영됨
# 원본의 값도 변경이 됨 ㄷㄷ 개신ㅇ기
arr_slice[1]=1234
print(arr_slice)
print(a)

arr_slice[:]=500

[  25 1234   49]
[1000    1 1000    9 1000   25 1234   49   64   81]


In [187]:
a=np.arange(10)**2
print(a)
# 훼손시키지 않고 변경시키기
arr_slice=a[5:8].copy() # copy()를 통해 별도 메모리에 복사를 했기 때문에 원본을 보존한다.
print(arr_slice)
arr_slice[:]=100
print(arr_slice)

print(a)

[ 0  1  4  9 16 25 36 49 64 81]
[25 36 49]
[100 100 100]
[ 0  1  4  9 16 25 36 49 64 81]


In [195]:
# 1~9까지 3x3 배열을 만들어보자
arr2d=np.arange(1,10).reshape(3,3)
print(arr2d)

print(arr2d[0]) # 1차원 배열
# 2를 출력하는 두가지 방법
print(arr2d[0][1])
print(arr2d[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
2


In [215]:
# 1~12까지 2x2x3 행렬을 만들어보자
arr3d=np.arange(1,13).reshape(2,2,3)
print(arr3d)
print(arr3d[0])
print(arr3d[0,1])
print(arr3d[1,0])
print(arr3d[1,0,1])
# 원본 훼손 없이 첫번째 2x3 행렬에 100으로 값을 변경하고자 한다.
arr=arr3d[0].copy()
arr[0]=100
print(arr)

#10,11출력
# print(arr3d[1,1,0:2])
print(arr3d[1,1][:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[4 5 6]
[7 8 9]
8
[[100 100 100]
 [  4   5   6]]
[10 11]


In [219]:
a=np.arange(8)**2
print(a)

mask=np.array([1,1,3,5]) 
print(a[mask])

[ 0  1  4  9 16 25 36 49]
[ 1  1  9 25]


In [222]:
mask2d=np.array([[3,4],[2,5]])
print(mask2d)
print(a)
print(a[mask2d])

[[3 4]
 [2 5]]
[ 0  1  4  9 16 25 36 49]
[[ 9 16]
 [ 4 25]]


In [227]:
# 0~11 의 값을 가진 3x4 행렬을 만들고
arr=np.arange(12).reshape(3,4)
print(arr)
# 4보다 큰 값을 가지는 값들을 출력하시오.
print(arr[arr>4]) # 차원 변경

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 5  6  7  8  9 10 11]


In [230]:
arr[arr>4] =0 #얘는 차원변경이 없다.
print(arr)  

[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


## numpy 크기(차원) 변경
- ravel: 1차원 변경
- reshape: 지정한 차원으로 변경
- T: 전치(transpose)

In [236]:
a=np.arange(12).reshape(3,4)
print(a)

a.ravel()
print(a.ravel())
a.reshape(-1)
print(a.reshape(-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [245]:
print(a) # (3,4)
a=a.T
print(a) # (4,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [248]:
#4,8,5,9 출력
a[:2,1:].ravel()

array([4, 8, 5, 9])

In [253]:
# 3,7,11
print(a[3],a[3].shape)
print(a[3,:],a[3,:].shape)
print(a[3:,:],a[3:,:].shape)

[ 3  7 11] (3,)
[ 3  7 11] (3,)
[[ 3  7 11]] (1, 3)


In [268]:
print(a)
# 0,4,1,5,2,6,3,7
a[:,:2] # 행은 다 필요 (axis0)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [271]:
print(a)
print(a.shape)
# 1,5
print(a[1,:2] )
# 행을 1로 고정했기 때문에 차원이 1 차원으로 고정됨--> 차원을 유지하고 싶으면 슬라이싱 사용
print(a[1,:2].shape) 
# 차원 유지
print(a[1:2,:2])
print(a[1:2,:2].shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)
[1 5]
(2,)
[[1 5]]
(1, 2)


In [4]:
import numpy as np
# "python",7, "numpy",100,9999
# 위의 값들을 Numpy 배열 선언하고 타입을 확인
custom_list=["python",7, "numpy",100,9999] # 파이썬 리스트는 타입상관 x
nd_array=np.array(custom_list) # dimension array가 됨
print(type(nd_array), nd_array.dtype)

<class 'numpy.ndarray'> <U11


In [5]:
# 0이 10개 채워진 1차원 배열 생성하여 출력
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# 0이 10개 채워진 (5,5) 형태의 2차원 배열 생성하여 출력
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# 아래와 같은 결과가 나오도록 넘파이 배열을 만들어보자
# [0.   0.5 1.  ]
np.arange(0, 1+0.5, 0.5)
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [22]:
# 0부터 9까지 3제곱한 값을 넘파이 배열로 만들어보자
nd_array=np.arange(10)**3
print(nd_array)
# 위에서 만든 넘파이 배열에서 8를 출력해보자
nd_array[2]
# 27 64 125 를 출력해보자
nd_array[3:6]
# 64 이상의 요소만 출력
nd_array[4:]
python_64=nd_array>=64
python_64
nd_array[python_64]

int_list = list(range(4,10))
int_list
nd_array[int_list]

[  0   1   8  27  64 125 216 343 512 729]


array([ 64, 125, 216, 343, 512, 729], dtype=int32)

In [42]:
# 경계가 1이고 내부가 0인 2차원 10x10배열을 만들자
tenarr=np.zeros((10,10))
# tenarr[0]=1
# tenarr[:,0]=1
# tenarr[-1]=1
# tenarr[:,-1]=1
# print(tenarr)

tenarr[[0,-1],:]=1

#tenarr[:,[0,-1]]=1
print(tenarr)

# ones=np.ones((10,10))
# ones[1:-1,1:-1]=0
# print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [46]:
# 5x3매트릭스에 3x2매트릭스를 곱해서 결과를 출력
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
print(a@b)
np.ones((5,3)) @ np.ones((3,2))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [49]:
# 행값이 0에서 4인 5x5 매트릭스 만들기
four=np.zeros((5,5))
four_=np.arange(5)
four=four+four_
four

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## 데이터 쪼개기
np.hsplit()

In [66]:
# 0~11 2x6 행렬을 만들자
a=np.arange(12).reshape(2,6)
print(a)
np.hsplit(a,3) # hsplit은 축이 기준
print(np.hsplit(a,3))
type(a)
type(np.hsplit(a,3))
np.hsplit(a,3)[1][1,1]
np.hsplit(a,3)[1][1][1]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


9

In [68]:
print(a)
np.hsplit(a,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[0, 1],
        [6, 7]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10]]),
 array([[ 5],
        [11]])]

In [81]:
# 분할을 2x3, 2x1, 2x2 분할 하세요
print(a)
np.hsplit(a,(3,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [82]:
print(a)
np.vsplit(a,1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])]

In [84]:
a=np.arange(18).reshape(3,6)
print(a)
np.vsplit(a,(1,2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

# pandas(python data analysis library)
2차원 데이터를 효율적으로 가공할 수 있는 기능을 제

In [2]:
! pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## pandas 데이터 형식
  pandas = series 와 series의 집합인 dataframe  
### series
- 1차원 데이터
- index와 데이터가 1:1로 맵핑되는 것
- 엑셀시트의 하나의 컬럼(열)
### dataframe
- series가 여러개 모인 것


### series 생성방법
- 딕셔너리(키가 인덱스가 됨), 리스트(인덱스를 자동으로 넘버링)로 생성가능 

In [3]:
import pandas as pd

C:\Users\OWNER\AppData\Local\Temp\ipykernel_14788\4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [91]:
dict_data={'a':1, 'b':2, 'c':3}

series_data=pd.Series(dict_data, name='score')
series_data, type(series_data)
print(series_data)

a    1
b    2
c    3
Name: score, dtype: int64


In [96]:
list_data = ['2020-10-11',3.14, 'ABC', 100, True]
series_data=pd.Series(list_data)
series_data, type(series_data)
# 시리즈는 리스트의 값이 자동으로 인덱스로 맵핑된 것.
series_data=pd.Series(list_data, index=[1,3,5,7,9], name='exam') # 인덱스 임의 설정 가능
print(series_data) # name은 컬럼명,
# value들은 모두 1차원 ~~ 이게 중요한 포인트임~~~

1    2020-10-11
3          3.14
5           ABC
7           100
9          True
Name: exam, dtype: object


## dataframe
행과 열로 이루어진 2차원 

In [ ]:
dict_data={'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9]}
# 키는 컬럼명으로,? 데이터프레임은 세개 ?ㅂ?
df=pd.DataFrame(dict_data)
print(df, type(df))

(   c0  c1  c2
 0   1   4   7
 1   2   5   8
 2   3   6   9,
 pandas.core.frame.DataFrame)

   c0  c1  c2
0   1   4   7
1   2   5   8
2   3   6   9 <class 'pandas.core.frame.DataFrame'>


In [105]:
df=pd.DataFrame(dict_data, index=['a','b','c'],columns=['cg','cv','cs'])
print(df)

    cg   cv   cs
a  NaN  NaN  NaN
b  NaN  NaN  NaN
c  NaN  NaN  NaN


In [231]:
titanic = pd.read_csv("files/titanic.csv")
type(titanic)

pandas.core.frame.DataFrame

In [113]:
titanic.columns # 컬럼명 확인
titanic.head(3) # 상위 3개 출력

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [115]:
titanic.tail() # 개수 디폴트 5개이고 원하는 개수 찌겅주기~~

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [117]:
titanic.shape # 행, 열의 크기 확인

(891, 12)

In [119]:
titanic.info() # 전반적인 정보를 제공

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [120]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [123]:
names=titanic['Name']
names.head(5)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [125]:
names=titanic.Name
type(names), names.shape

(pandas.core.series.Series, (891,))

In [126]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [136]:
passenger=titanic[['Sex','Age']] # (891,2)가 되는 2차원이여야 해서 대괄호가 2개
passenger.head(5)
#passenger.shape

p= passenger['Age']>35
p
passenger['Age'][p]
above_35=passenger[passenger['Age']>35]
above_35.head(10)

Sex   Age
1   female  38.0
6     male  54.0
11  female  58.0
13    male  39.0
15  female  55.0
25  female  38.0
30    male  40.0
33    male  66.0
35    male  42.0
40  female  40.0

isin() : True/False 반환

In [138]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [143]:
a= titanic['Pclass'].isin([1]) #'PClass' 시리즈 안에 1이 포함되어 있냐 아니냐 불리언으로 
# 왜 대괄호일까!?
titanic[a]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
11            12         1       1   
23            24         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
11       0    113783  26.5500         C103        S  
23       0    113788  35.5000           A6        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[216 rows x 12 columns]

In [152]:
import numpy as np
passenger.head()
# p=passenger['Age'].isin([20,41])
p=passenger['Age'].isin(np.arange(20,41)) # demansion arange사용하기~
titanic[p]


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          885         0       3   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
884      0   SOTON/OQ 392076   7.0500   NaN        S  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[389 rows x 12 columns]

In [155]:
titanic.head(20)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


## isna, notna
- isna(): 결측값은 True  
- notna(): 결측값은 False  
(결측값: 존재하지 않는 null 값)

In [157]:
passenger.head(10)

Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0
5    male   NaN
6    male  54.0
7    male   2.0
8  female  27.0
9  female  14.0

In [158]:
passenger['Age'].isna()[0:7]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
Name: Age, dtype: bool

In [160]:
passenger[passenger['Age'].isna()]

Sex  Age
5      male  NaN
17     male  NaN
19   female  NaN
26     male  NaN
28   female  NaN
..      ...  ...
859    male  NaN
863  female  NaN
868    male  NaN
878    male  NaN
888  female  NaN

[177 rows x 2 columns]

In [162]:
passenger[passenger['Age'].notna()]

Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
885  female  39.0
886    male  27.0
887  female  19.0
889    male  26.0
890    male  32.0

[714 rows x 2 columns]

### 결측치 제거
dropna(axis=0): 결측치가 들어있는 행을 삭제
- axis=1: 열 삭제

In [163]:
titanic.info()  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [165]:
# cabin 이라는 변수에 name과 cabin 컬럼을 추출해서 담아보자
cabin=titanic[['Name','Cabin']]
cabin

Name Cabin
0                              Braund, Mr. Owen Harris   NaN
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                               Heikkinen, Miss. Laina   NaN
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                             Allen, Mr. William Henry   NaN
..                                                 ...   ...
886                              Montvila, Rev. Juozas   NaN
887                       Graham, Miss. Margaret Edith   B42
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  C148
890                                Dooley, Mr. Patrick   NaN

[891 rows x 2 columns]

In [167]:
cabin[cabin['Cabin'].notna()].head()
cabin.head()

Name Cabin
0                            Braund, Mr. Owen Harris   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                             Heikkinen, Miss. Laina   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                           Allen, Mr. William Henry   NaN

In [175]:
cabin.dropna().head()

Name Cabin
1   Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
6                             McCarthy, Mr. Timothy J   E46
10                    Sandstrom, Miss. Marguerite Rut    G6
11                           Bonnell, Miss. Elizabeth  C103

In [176]:
cabin.dropna(axis=1).head() # 행 도 지울 수 있다. 
# 다른 행에 영향이 안가도록!

Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

### Pandas에서 행과 열을 선택
df. loc[행인덱스값, 열인덱스값]  
= 행인덱스값에는 boolean indexing을 할 수 있다.  
  
df. iloc[행인덱스, 열인덱스]  

In [181]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [183]:
titanic.loc[:5,'Name'] # 인덱스 넘버가 아니라 인덱스 값임.!

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
Name: Name, dtype: object

In [195]:
# 3등석 고객 중 살아있는 사람의 목록을 출력
condition=(titanic['Survived']==1) & (titanic['Pclass']==3) # 괄호 붙이기.

a=titanic.loc[condition] # head로 해도 되고.. ㅓ어쩌구..똑같음 결국

In [197]:
len(a)

119

In [201]:
# 35세 초과된느 사람들의 이름과 나이를 출력
name35=titanic.loc[titanic['Age']>35, ['Name','Age']]
name35.head()


Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
6                             McCarthy, Mr. Timothy J  54.0
11                           Bonnell, Miss. Elizabeth  58.0
13                        Andersson, Mr. Anders Johan  39.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0

In [205]:
name35.iloc[[1,2,3],0]='No Name'
name35

Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
6                                              No Name  54.0
11                                             No Name  58.0
13                                             No Name  39.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
..                                                 ...   ...
865                           Bystrom, Mrs. (Karolina)  42.0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
873                        Vander Cruyssen, Mr. Victor  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
885               Rice, Mrs. William (Margaret Norton)  39.0

[217 rows x 2 columns]

In [207]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [210]:
# passengerid,survived,pclass->iloc활용
t=titanic.iloc[:,0:3] # 인덱싱 사용이라 슬라이싱 사용 ...
t

PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [235]:
# 3등석이면서 생존자. iloc사용
titanic = pd.read_csv("files/titanic.csv")

t=(titanic['Survived']==1) & (titanic['Pclass']==3)
t
titanic.iloc[t,3:5]='No Name'
titanic.head(30)

titanic.iloc[t.values,3]
print(type(t.values)) ## true에 해당되는 것ㅁ만 나오게 됨
print(type(t)) ## 모든 열이 다 나옴

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


## pandas 데이터 통계
- df.mean(): 평균값    
- df.median(): 중앙값  
- df.dscribe(): 통계 데이터 요약  
- df.agg([func1,func2...]):   

In [4]:
titanic = pd.read_csv("files/titanic.csv")

In [237]:
titanic['Age'].mean()

29.69911764705882

In [239]:
titanic['Age'].median()

28.0

In [240]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [242]:
titanic[['Age','Fare']].describe()

Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [13]:
titanic.agg({'Age':['min','max','median'],
            'Fare':['min','max','mean']})

Age        Fare
min      0.42    0.000000
max     80.00  512.329200
median  28.00         NaN
mean      NaN   32.204208

In [28]:
titanic
#titanic.agg(['min','max','mean'])

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### groupby()

In [8]:
titanic.groupby(['Sex','Pclass'])[['Age','Fare']].agg(['mean','min','max'])

Age                    Fare                   
                    mean   min   max        mean      min       max
Sex    Pclass                                                      
female 1       34.611765  2.00  63.0  106.125798  25.9292  512.3292
       2       28.722973  2.00  57.0   21.970121  10.5000   65.0000
       3       21.750000  0.75  63.0   16.118810   6.7500   69.5500
male   1       41.281386  0.92  80.0   67.226127   0.0000  512.3292
       2       30.740707  0.67  70.0   19.741782   0.0000   73.5000
       3       26.507589  0.42  74.0   12.661633   0.0000   69.5500

In [9]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
titanic.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [17]:
survived=titanic.groupby('Sex')['Survived'].mean()
(survived*100)

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

### pivot_table()

In [29]:
titanic.pivot_table(index='Sex',values='Survived',aggfunc=['mean','sum'])

mean      sum
        Survived Survived
Sex                      
female  0.742038      233
male    0.188908      109

In [44]:
# 성별로 좌석 등급별 나이와 생존률의 평균
t=titanic.groupby(['Sex','Pclass'])[['Age','Survived']].mean()

t.iloc[:,1]=t['Survived']*100
t


Age   Survived
Sex    Pclass                      
female 1       34.611765  96.808511
       2       28.722973  92.105263
       3       21.750000  50.000000
male   1       41.281386  36.885246
       2       30.740707  15.740741
       3       26.507589  13.544669

In [47]:
titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [49]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [53]:
titanic['Cabin'].value_counts(dropna=False) # NaN 도 카운트 

Cabin
NaN            687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: count, Length: 148, dtype: int64

In [54]:
titanic.groupby('Sex')['Survived'].value_counts()

Sex     Survived
female  1           233
        0            81
male    0           468
        1           109
Name: count, dtype: int64

In [ ]:
# numpy 설치 
! pip install numpy
# 주피터에선 !를 꼭 붙여줘야함

import numpy as np
import pandas as pd


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


C:\Users\OWNER\AppData\Local\Temp\ipykernel_13604\3607753176.py:6: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [ ]:
titanic = pd.read_csv("files/titanic.csv")
type(titanic)

pandas.core.frame.DataFrame

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# 복습_groupby(), pivot_table()

In [ ]:
## 성별로 클래스별로 생존확률 집계
## pivot_table과 groupby를 각각 활용해서 데이터를 추출
# groupby 사용
g=titanic. groupby(['Sex','Pclass'])['Survived'].value_counts()
g
# pivot_table 사용


Sex     Pclass  Survived
female  1       1            91
                0             3
        2       1            70
                0             6
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
Name: count, dtype: int64

In [ ]:
titanic.pivot_table(index=['Sex','Pclass'],values='Survived',aggfunc='count')


Survived
Sex    Pclass          
female 1             94
       2             76
       3            144
male   1            122
       2            108
       3            347

In [ ]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic.shape

(891, 12)

In [ ]:
titanic.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
# 890번 행을 new_row라는 변수에 담아본다.
newrow=titanic.iloc[890,:]
newrow,type(newrow)

(PassengerId                    891
 Survived                         0
 Pclass                           3
 Name           Dooley, Mr. Patrick
 Sex                           male
 Age                           32.0
 SibSp                            0
 Parch                            0
 Ticket                      370376
 Fare                          7.75
 Cabin                          NaN
 Embarked                         Q
 Name: 890, dtype: object,
 pandas.core.series.Series)

## 열추가

In [ ]:
# 891 번째에 newrow 삽입
# loc 사용
titanic.loc[891]=newrow
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   
891          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   
891                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  3Pclass  
0        0         A/5 21171   7.2500   NaN        S      9.0  
1        0          PC 17599  71.2833   C85        C      3.0  
2        0  STON/O2. 3101282   7.9250   NaN        S      9.0  
3        0            113803  53.1000  C123        S      3.0  
4        0            373450   8.0500   NaN        S      9.0  
..     ...               ...      ...   ...      ...      ...  
887      0            112053  30.0000   B42        S      3.0  
888      2        W./C. 6607  23.4500   NaN        S      9.0  
889      0            111369  30.0000  C148        C      3.0  
890      0            370376   7.7500   NaN        Q      9.0  
891      0            370376   7.7500   NaN        Q      NaN  

[892 rows x 13 columns]

In [ ]:

# shape을 이용해서 수기로 삽입
# 열 추가
titanic['3Pclass']=titanic['Pclass']*3 # titanic은 series임
# 넣고싶은 열의 이름을 정해주고 값도 지정
# 주의사항: 컬럼추가 시 dtype맞춰주기!! info()로 확인해서 하슈
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  3Pclass  
0      0         A/5 21171   7.2500   NaN        S        9  
1      0          PC 17599  71.2833   C85        C        3  
2      0  STON/O2. 3101282   7.9250   NaN        S        9  
3      0            113803  53.1000  C123        S        3  
4      0            373450   8.0500   NaN        S        9

In [ ]:
titanic.tail()

PassengerId  Survived  Pclass                                      Name  \
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   
891          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  3Pclass  
887  female  19.0      0      0      112053  30.00   B42        S        3  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S        9  
889    male  26.0      0      0      111369  30.00  C148        C        3  
890    male  32.0      0      0      370376   7.75   NaN        Q        9  
891    male  32.0      0      0      370376   7.75   NaN        Q        9

## 행추가

In [ ]:

# 행 추가
# append() 메소드로 행 추가하기 (딕셔너리 활용)==> pandas version 2.2.0에서 함수 사라짐
# 시리즈를 추가할 땐 딕셔너리를 사용하는게 당연한거~
# 키와 값, 인덱스와 값이 추가되는 느낌~

#titanic.append({'PassengerId':893, 'Survived':1, 'Pclass':1},ignore_index=True)

# 주의사항: 꼭 ignore_index=True 로 인덱스를 무시하도록 꼭 명시해주기 그래야 맨 밑에 어펜딩이 됨
# 꼭 끝에만 데이터를 삽입할 수 있는가? 

### 원하는 위치에 행 삽입하기
인덱스 정해줘서 concat

In [ ]:
# 중간에 삽입하기
insert_index= 891
pre_df=titanic.iloc[:insert_index,:]
# pre_df.tail()
after_df=titanic.iloc[insert_index:,:]
# after_df
# 슬라이스 연산자를 줘서 구조로.?

# 새로운 데이터 프레임을 만들어줘야함 
# 데이터 프레임은 2차원임.-> 대괄호 두개
new_df=pd.DataFrame([[892, 1, 1, 'kavin','male',40.0,1,2,'T123',45.8,np.nan,'S',6]],columns=titanic.columns) # 컬럼값 정해주기!
new_df

PassengerId  Survived  Pclass   Name   Sex   Age  SibSp  Parch Ticket  \
0          892         1       1  kavin  male  40.0      1      2   T123   

   Fare  Cabin Embarked  3Pclass  
0  45.8    NaN        S        6

In [ ]:
new_df_=pd.concat([pre_df,new_df,after_df],ignore_index=True)
new_df_.tail()

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   
891          892         1       1                                     kavin   
892          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  3Pclass  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S        9  
889    male  26.0      0      0      111369  30.00  C148        C        3  
890    male  32.0      0      0      370376   7.75   NaN        Q        9  
891    male  40.0      1      2        T123  45.80   NaN        S        6  
892    male  32.0      0      0      370376   7.75   NaN        Q        9

In [ ]:
print(pd.__version__)

2.2.0


### 원하는 위치에 열 삽입하기
insert() 사용

In [ ]:
titanic.insert(3,'Custom_P',titanic['3Pclass']/3)

In [ ]:

titanic.head()

PassengerId  Survived  Pclass  Custom_P  \
0            1         0       3       3.0   
1            2         1       1       1.0   
2            3         1       3       3.0   
3            4         1       1       1.0   
4            5         0       3       3.0   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  3Pclass  
0      0         A/5 21171   7.2500   NaN        S        9  
1      0          PC 17599  71.2833   C85        C        3  
2      0  STON/O2. 3101282   7.9250   NaN        S        9  
3      0            113803  53.1000  C123        S        3  
4      0            373450   8.0500   NaN        S        9

## 행/열 삭제
- drop() 사용  
축만 설정해주면 됨  
인덱스도 사용될 듯

In [ ]:
# 행 삭제
titanic.drop(range(800,892),axis=0) # numpy의 arange 써도 될 듯?>
titanic.tail() # 원본은 그대로임
a=titanic.drop(range(800,892),axis=0)
a.tail()

# 열 삭제
titanic.drop(titanic['3Pclass']) # 이거는 데이터만 사라짐
titanic.drop(columns=['3Pclass']) # 이렇게도 되던데?!
titanic.drop(columns=['3Pclass'],axis=1) # 컬럼 자체를 삭제하기

PassengerId  Survived  Pclass  Custom_P  \
0              1         0       3       3.0   
1              2         1       1       1.0   
2              3         1       3       3.0   
3              4         1       1       1.0   
4              5         0       3       3.0   
..           ...       ...     ...       ...   
887          888         1       1       1.0   
888          889         0       3       3.0   
889          890         1       1       1.0   
890          891         0       3       3.0   
891          891         0       3       3.0   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   
891                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  
891      0            370376   7.7500   NaN        Q  

[892 rows x 13 columns]